version: '2.4'
networks:
  cassandranet:
services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    hostname: cassandra1
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60
    ports:
      - "9042:9042"
    volumes:
      - ./data/cassandra1:/var/lib/cassandra
      - ./etc/cassandra1:/etc/cassandra
    networks:
      - cassandranet
    environment: &envi
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_CLUSTER_NAME=NBD
      - CASSANDRA_DATACENTER = dc1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_USER=cassnadra
      - CASSANDRA_PASSWORD=cassandrapassword
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
    mem_limit: 2gb
    mem_reservation: 128M
  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    hostname: cassandra2
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60
    networks:
      - cassandranet
    ports:
      - "9043:9042"
    depends_on:
      - cassandra1
    volumes:
      - ./data/cassandra2:/var/lib/cassandra
      - ./etc/cassandra2:/etc/cassandra
    environment: *envi
    mem_limit: 2gb
    mem_reservation: 128M
#  cassandra3:
#    image: cassandra:latest
#    container_name: cassandra3
#    hostname: cassandra3
#    healthcheck:
#      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
#      interval: 5s
#      timeout: 5s
#      retries: 60
#    networks:
#      - cassandranet
#    ports:
#      - "9044:9042"
#    volumes:
#      - ./data/cassandra3:/var/lib/cassandra
#      - ./etc/cassandra3:/etc/cassandra
#    depends_on:
#      - cassandra2
#    environment: *envi
#    mem_limit: 2gb
#    mem_reservation: 128M